DROP DATABASE IF EXISTS ESCUELA;
CREATE DATABASE ESCUELA;
USE ESCUELA;
CREATE TABLE ALUMNO(
DNI CHAR(9) PRIMARY KEY,
NOMBRE VARCHAR(20)NOT NULL,
APELLIDO1 VARCHAR(20)NOT NULL,
APELLIDO2 VARCHAR(20)NOT NULL,
TELEFONO INT(9),
F_NACIMIENTO DATE NOT NULL
);

CREATE TABLE CICLO(
ID INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(20),
CURSOS INT NOT NULL,
NIVEL ENUM('MEDIO', 'SUPERIOR')
);

CREATE TABLE MODULO(
ID INT AUTO_INCREMENT,
NOMBRE VARCHAR(50) NOT NULL,
CURSO INT NOT NULL,
HORAS INT NOT NULL,
ID_CICLO INT NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY (ID_CICLO)REFERENCES CICLO(ID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

CREATE TABLE MATRICULA(
DNI_ALUMNO CHAR(9),
ID_MODULO INT,
ANHO INT(4),
NOTA DECIMAL(4,2),

FOREIGN KEY(DNI_ALUMNO)REFERENCES ALUMNO(DNI)
ON DELETE RESTRICT
ON UPDATE CASCADE,

FOREIGN KEY (ID_MODULO)REFERENCES MODULO(ID)
ON DELETE RESTRICT
ON UPDATE CASCADE
);